spring:
  application:
    name: turing
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: createe-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

api:
  security:
    token:
      secret: ${JWT_SECRET}

admin:
  seed:
    email: ${ADMIN_EMAIL:adm@gmail.com}
    senha: ${ADMIN_SENHA:123}
    cpf: ${ADMIN_CPF:00000000000}