spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: turing
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

    resend:
      api-key: ${RESEND_API_KEY}
      sender-email: ${RESEND_SENDER_EMAIL}
      sender-name: "Seu Espaço UnB"

api:
  security:
    token:
      secret: ${JWT_SECRET}

admin:
  seed:
    email: ${ADMIN_EMAIL:adm@gmail.com}
    senha: ${ADMIN_SENHA:123}
    cpf: ${ADMIN_CPF:00000000000}

